### ISSUE TITLE
Extend image policy with numerical ordering

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/image-reflector-controller#102]
While alphabetical ordering works great with image tags that contain a RFC3339 timestamp, it's not suitable for CI build IDs, as these are numbers with no padding. 

I propose we introduce a new ordering option called `numerical` to be able to correct detect the latest build for tags in the format `<PREFIX>-<BUILD_ID>`. 

Example:

```yaml
kind: ImagePolicy
spec:
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<id>.*)'
    extract: '$id'
  policy:
    numerical:
      order: asc
```

Given the tags `main-845d3a80-100` and `main-3e32dc8a-2` the `numerical` policy, unlike  `alphabetical`, will chose `main-3e32dc8a-100` as the latest build.
