### ISSUE TITLE
Command: flux get image update return unknown error: Unauthorized message 

### ISSUE THREAD

**Issue by hieu29791** [fluxcd/image-reflector-controller#111]
Hi, I set up Image Auto Update following this guide: https://toolkit.fluxcd.io/guides/image-update/  
I use EKS, ECR private registry, and bitbucket. Components such as Kustomize, Helm, Source controller work fine. But Auto Update Image shows errors. Here is the details:  
Result of command:  
**flux get image repository**
![image](https://user-images.githubusercontent.com/10827875/108989156-e061b000-76c7-11eb-9f6e-3859775f6145.png)
**flux get image policy**
![policy](https://user-images.githubusercontent.com/10827875/108989671-709ff500-76c8-11eb-8907-542f70b2b97f.png)  
**flux get image update**
![image](https://user-images.githubusercontent.com/10827875/108989764-8ad9d300-76c8-11eb-922e-de14f58ee3db.png)
Image update show errors so I guess flux can't update image to my deployment.
Here is a summary of the yaml content  
**Image Auto Update**: 
```
# ImageRepository to tell Flux which container registry to scan for new tags:
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: nginx-test
  namespace: flux-system
spec:
  image: xxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/fluxcd/nginx
  interval: 1m0s
  secretRef:
    name: ecr-credentials
---
# ImagePolicy to tell Flux which semver range (or another tools) to use when filtering tags:
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: nginx-test
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-test
  filterTags:    
    pattern: '^master-.+'    
  policy:
    alphabetical:
      order: asc 
---
# ImageUpdateAutomation to tell Flux which Git repository to write image updates to
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: master
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 1m0s
  update:
    strategy: Setters
```
**ECR cron**:  
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - delete
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: ecr-credentials-sync
roleRef:
  kind: Role
  name: ecr-credentials-sync
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
  # Uncomment and edit if using IRSA
  # annotations:
  #   eks.amazonaws.com/role-arn: <role arn>
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-credentials-sync
  namespace: flux-system
spec:
  suspend: false
  schedule: 0 */6 * * *
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-credentials-sync
          restartPolicy: Never
          volumes:
          - name: token
            emptyDir:
              medium: Memory
          initContainers:
          - image: amazon/aws-cli
            name: get-token
            imagePullPolicy: IfNotPresent
            # You will need to set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables if not using
            # IRSA. It is recommended to store the values in a Secret and load them in the container using envFrom.
            envFrom:
            - secretRef:
                name: aws-credentials
            env:
            - name: REGION
              value: ap-southeast-1 # change this if ECR repo is in a different region
            volumeMounts:
            - mountPath: /token
              name: token
            command:
            - /bin/sh
            - -ce
            - aws ecr get-login-password --region ${REGION} > /token/ecr-token
          containers:
          - image: bitnami/kubectl
            name: create-secret
            imagePullPolicy: IfNotPresent
            env:
            - name: SECRET_NAME
              value: ecr-credentials
            - name: ECR_REGISTRY
              value: xxxxx.dkr.ecr.ap-southeast-1.amazonaws.com # fill in the account id and region
            volumeMounts:
            - mountPath: /token
              name: token
            command:
            - /bin/bash
            - -ce
            - |-
              kubectl delete secret --ignore-not-found $SECRET_NAME
              kubectl create secret docker-registry $SECRET_NAME \
                --docker-server="$ECR_REGISTRY" \
                --docker-username=AWS \
                --docker-password="$(</token/ecr-token)"
```
**AWS-credentials secret**
```
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: flux-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: xxxxxxxxxxxxxxxxx
  AWS_SECRET_ACCESS_KEY: xxxxxxxxxxxxxxxx
```
Could you show me why errors happen? Thanks
