### ISSUE TITLE
Insufficient controller permissions

### ISSUE THREAD

**Issue by manu11th** [fluxcd/image-reflector-controller#114]
We have applied the image-reflection-controller with the default controller.yaml generated by `kustomize build /config/default` to our GKE cluster.
Unfortunately this results in controller error logs because of the absence of multiple permissions for both the `image-reflector-manager-role` `ClusterRole` and the `image-reflector-leader-election-role` `Role`.

We made the controller work by adding the `patch` verb for the `image-reflector-leader-election-role` and by adding the following to the `image-reflector-manager-role`:

```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - get
```

Does anyone else faces this issue?
