### ISSUE TITLE
Rollbacks with image policy?

### ISSUE THREAD

**Issue by nomeelnoj** [fluxcd/image-reflector-controller#116]
Hey All--just deployed fluxv2 to our dev cluster and am SUPER excited about it! BIG improvement, and the last version served us so well, we cant wait to see the things about the new version we have not even unlocked.

I was playing around with the ImagePolicy, and wondered how you would do rollbacks in the event of a big issue if the policy only works on incrementing `semver` versions.

For example, I have this policy:
```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: my-image
  namespace: flux-system
spec:
  filterTags:
    extract: $1
    pattern: ^dev-v(.*)
  imageRepositoryRef:
    name: my-image
  policy:
    semver:
      range: 2.x.x-0
```
The image tag we are using is `dev-v2.x.x-<build-id>`.  Doing it this way allows us to simply re-tag an image with `stg` and the staging cluster picks it up and deploys automatically (same for prod when we promote).  This currently works with our _expected_ workflow, but what happens when we need to roll back?

Say we have just deployed `v2.31.0-34` and now we need a way to re-deploy `v2.29.3-33`.  Is there any way to do this or is it on the roadmap? Or is the expected path that we would just create a patch and create `v2.31.1-35`?  That would be particularly difficult in the case of a rollback, as we would need to revert the commit in our git repo versus just trigger a CI job that rebuilds a particular tag (or better yet, find a way to tell flux to grab an old image temporarily).

Any thoughts around this?

Thanks so much in advance!
