### ISSUE TITLE
Image Repository failing to find secret when Image Repo has multiple slashes in the name

### ISSUE THREAD

**Issue by rayterrill** [fluxcd/image-reflector-controller#127]
We use Nexus Repo Manager for storing docker images internally, and the path to images contains multiple slashes (i.e. https://ourrepo.ourdomain.com:8083/repository/internal/myimage). It looks like when the we configure the ImageRepository config, it's parsing the repository as ourrepo.ourdomain.com:8083, not the full path of ourrepo.ourdomain.com:8083/repository/internal.

```
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: myimage
  namespace: infraops
spec:
  image: ourrepo.ourdomain.com:8083/repository/internal/myimage
  interval: 1m0s
  secretRef:
    name: regcred
```

Error received:
```
me@myhost:~/Fluxv2-InfraOps/base$ flux get image repository -n infraops
NAME            READY   MESSAGE                                                                         LAST SCAN       SUSPENDED 
myimage False   auth for "ourrepo.ourdomain.com:8083" not found in secret infraops/regcred                 False
```

In our regcred secret, our secret is defined like this:
```
{"auths":{"ourrepo.ourdomain.com:8083/repository/internal":{"username":"REDACT","password":"REDACT","email":"REDACT","auth":"REDACT"}}}
```

This repo URL structure works fine for our deployment (and this also worked correctly for us in fluxv1 because it was just an annotation on the deployment).
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimage
  namespace: infraops
  labels:
    app: myimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: myimage
        image: ourrepo.ourdomain.com:8083/repository/internal/myimage:latest
        ports:
        - name: http-port
          containerPort: 80
      imagePullSecrets:
      - name: regcred
```
