### ISSUE TITLE
Image reflector does not update most recent images

### ISSUE THREAD

**Issue by jluque0101** [fluxcd/image-reflector-controller#145]
Following the example from [docs](https://fluxcd.io/docs/components/image/imagepolicies/#examples)
Image policy:
```
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: app
spec:
  imageRepositoryRef:
    name: app-repo
  filterTags:
    pattern: '^staging-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
     numerical:
      order: asc
```
Docker container tags:
```
staging-b7a90d9-552613297731
staging-34769fa-551067109282849
```
I would expect that **staging-b7a90d9-552613297731** is considered as newer and therefore container tag reference would be updated however  **staging-34769fa-551067109282849** is being selected.
Changing from **asc** to **desc** will pick up the most recent image, but shouldn't be the case right? 

Same policy but with different environment within the pattern section does not work as expected either.

Cloud you please clarify if this is the right way of doing it please? Thanks.
