### ISSUE TITLE
auth for "https:" not found

### ISSUE THREAD

**Issue by SomtochiAma** [fluxcd/image-reflector-controller#146]
Creating an Image repository with this YAML
```
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: inspector
  namespace: flux-system
spec:
  image: https://quay.io/repository/adoreme/inspector
  interval: 1m0s
  secretRef:
    name: quay-secret
```

and this docker-registry secret
```
{"auths":{"https://quay.io":{"username":"****","password":"****","auth":"****"}}}
```

results in this error
```
auth for "https:" not found in secret flux-system/quay-secret
```

This issue is gotten from [this message on slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1621241461166600)
