### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by ZeroDeltaAlpha** [fluxcd/image-reflector-controller#156]
### The Bug
When using the following YAML as a image registry
```yaml
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  image: quay.io/bitnami/sealed-secrets-controller
  interval: 10ms
```
the following log is returned form the image reflector
```
Get "https://quay.io/v2/bitnami/sealed-secrets-controller/tags/list?next_page=gAAAAABg2cH18ij9VQofd4q8kC_C8f3H5IG4kQ4FGSpehDR3RkIdYWz0Xw5eqhDFSdhvlUYyB_t2hbgG_-NhNIBGadfR4_SjO0qOi5GavRdVlpN6tvcb8ek%3D&n=50": context deadline exceeded
```
This only seems to happen on quay.io.

### Replication 

apply the above YAML to a cluster and wait for a fetch of version tags.

Observe the logs for the mentioned message

### Versions
flux version 0.15.2
ghcr.io/fluxcd/image-reflector-controller:v0.9.1
