### ISSUE TITLE
Allow exclusion of cosign objects from the image repository database

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/image-reflector-controller#167]
When using [cosign](https://github.com/sigstore/cosign) to sign container images, a standalone object is push to the registry. Our image scanner thinks this is a valid container image tag (GHCR thinks that too) and could potentially crash live system if an image policy matches the cosign object.

For example I've signed [flagger-loadtester](https://github.com/orgs/fluxcd/packages/container/package/flagger-loadtester), GHCR shows the signature object as a container image tag:

<img width="756" alt="Screenshot 2021-08-24 at 16 38 27" src="https://user-images.githubusercontent.com/3797675/130626741-24d1790f-f012-41c6-b274-da05aeeb20fe.png">

As expected Flux adds this tag to its database:

```console
$ flux create image repository flagger-loadtester --image ghcr.io/fluxcd/flagger-loadtester --interval 20m

$ flux get images all
NAME                              	READY	MESSAGE                      	LAST SCAN                	SUSPENDED 
imagerepository/flagger-loadtester	True 	successful scan, found 2 tags	2021-08-24T16:08:15+03:00	False 
```

To avoid deploying cosign signatures as container images onto clusters, I propose we add a field to the `ImageRepository` API to allow people to exclude tags based on regex expression, e.g.:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: flagger-loadtester
  namespace: flux-system
spec:
  image: ghcr.io/fluxcd/flagger-loadtester
  interval: 20m0s
  exclusionList:
    - ".*sig$"
```
