### ISSUE TITLE
semver level policy

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-reflector-controller#25]
As mentioned in https://github.com/fluxcd/toolkit/discussions/107#discussioncomment-51846: instead of giving a range of versions, give the part of the version that's allowed to be updated, e.g., `patch` or `minor`.

```yaml
policy:
  semver:
    level: patch
```

.. except this doesn't work without a base version, and supplying a base version would in effect be giving a version range. So maybe not that useful.

**Comment by squaremo** [comment]
It might work as a higher-level object, like "keep track of the versions of all these images":

```yaml
kind: ImageVersionPolicy
spec:
  imageRepositoryRef:
    name: alpine
  policy:
    semver:
      level: patch
```

which would give rise to `ImagePolicy` objects for each major.minor, giving the highest patch version. Again, not sure how useful this is, ultimately. It's probably better to use this in reference to a specific image, e.g., the one in use by a workload.
