### ISSUE TITLE
image-reflector-controller cannot pull image list

### ISSUE THREAD

**Issue by ccodreanu** [fluxcd/image-reflector-controller#289]
We upgraded from 0.19.2 to 0.19.3 and our Image Policies are getting spammed with:

```
image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty
```

while Image Repositories show:

```
image-reflector-controller  GCR authentication failed: registry provider not configured for login
```

We see this happening on images like `k8s.gcr.io/sig-storage/snapshot-validation-webhook` which do not require auth to be pulled.

Image Repo and Policy:

```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: snapshot-validation-webhook
spec:
  image: k8s.gcr.io/sig-storage/snapshot-validation-webhook
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: snapshot-validation-webhook
spec:
  imageRepositoryRef:
    name: snapshot-validation-webhook
  policy:
    semver:
      range: ">=5.0.0"
```
