### ISSUE TITLE
Cannot determine latest tag for policy: version list argument cannot be empty 

### ISSUE THREAD

**Issue by leptonyu** [fluxcd/image-reflector-controller#294]
I got this error.

```yaml
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: plex
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: plex
  filterTags:
    pattern: '^(?P<ver>[0-9]+(\.[0-9]+){2})\.(?P<ts>[0-9]+)-.*'
    extract: '$ver'
  policy:
    semver:
      range: '1.x'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: plex
  namespace: flux-system
spec:
  image: plexinc/pms-docker
  interval: 5m0s
```

```
│   Type     Reason  Age                    From                        Message                                                                                                   
│   ----     ------  ----                   ----                        -------                                                                                                   
│   Normal   info    18m (x69 over 4h45m)   image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   18m (x9 over 18m)      image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    16m (x5 over 18m)      image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   15m (x14 over 16m)     image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    14m (x5 over 15m)      image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   14m (x9 over 14m)      image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    12m (x5 over 14m)      image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   12m (x9 over 12m)      image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    12m (x3 over 12m)      image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   9m40s (x9 over 9m41s)  image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    8m3s (x6 over 9m39s)   image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   4m52s (x9 over 4m53s)  image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    2m12s (x5 over 4m51s)  image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                              
│   Warning  error   116s (x9 over 118s)    image-reflector-controller  Cannot determine latest tag for policy: version list argument cannot be empty                             
│   Normal   info    11s (x5 over 115s)     image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3   
```

**Comment by darkowlzz** [comment]
Hi, thanks for reporting the issue.
I tried reproducing it but it seems to be working fine.
ImagePolicy status:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-08-03T18:56:58Z"
    message: 'Latest image tag for ''plexinc/pms-docker'' resolved to: 1.28.0.5999-97678ded3'
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  latestImage: plexinc/pms-docker:1.28.0.5999-97678ded3
  observedGeneration: 1
```
And there's just success event:
```
  Type    Reason  Age                    From                        Message
  ----    ------  ----                   ----                        -------
  Normal  info    2m35s (x3 over 2m35s)  image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3
```

Can you provide more details about your setup? Version of image-reflector-controller and overall flux version?

**Comment by leptonyu** [comment]
Hi @darkowlzz , the ImagePolicy object status is okay.
I got this error logs from image-reflector-controller, and as you can see, it creates event for ImagePolicy.

```
➜  flux git:(main) flux version                                   
flux: v0.31.4
helm-controller: v0.22.2
image-automation-controller: v0.23.5
image-reflector-controller: v0.19.4
kustomize-controller: v0.26.3
notification-controller: v0.24.1
source-controller: v0.25.10
```

Automation.
```Yaml
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: leptonyu@users.noreply.github.com
        name: leptonyu
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./clusters/nuc
    strategy: Setters
```

```
│ Status:                                                                                                                                                                         
│   Conditions:                                                                                                                                                                   
│     Last Transition Time:  2022-08-03T14:31:40Z                                                                                                                                 
│     Message:               Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3                                                                         
│     Reason:                ReconciliationSucceeded                                                                                                                              
│     Status:                True                                                                                                                                                 
│     Type:                  Ready                                                                                                                                                
│   Latest Image:            plexinc/pms-docker:1.28.0.5999-97678ded3                                                                                                             
│   Observed Generation:     12                                                                                                                                                   
│ Events:                                                                                                                                                                         
│   Type    Reason  Age                  From                        Message                                                                                                      
│   ----    ------  ----                 ----                        -------                                                                                                      
│   Normal  info    86s (x129 over 10h)  image-reflector-controller  Latest image tag for 'plexinc/pms-docker' resolved to: 1.28.0.5999-97678ded3  
```
