### ISSUE TITLE
Harbor webhook issues with fluxv2

### ISSUE THREAD

**Issue by venkatesh-mb** [fluxcd/image-reflector-controller#309]
Our flux auto deployment woroking without any issues.

But we are having loot of inconscity with Webhook to deploy latest image as soon as image pushed. 
As soon as we configure 1st time it's working without any issues, later after coupole tages it's stopped working.
We as below template to test our webhook.

```
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: harbor-receiver
  namespace: tenant-dev
spec:
  type: harbor
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: image.toolkit.fluxcd.io/v1beta1
      kind: ImageRepository
      name: application-testing
```
Any idea how can we troubleshoot this issue?

and second question relevent to same topic.

We have around 50 applications in each environment. Do we have create 50 yamls files for every imageRepositry? or is there any way we can manage all at a time.
