### ISSUE TITLE
Image repository port pruned from reflection request after 1000+ images

### ISSUE THREAD

**Issue by springroll12** [fluxcd/image-reflector-controller#343]
Hello all,

I'm experiencing an issue where an ImageRepository fails to find the latest tags when there are more than 1000 image tags in the repo. We run our docker repository over https on port 5000 (not 443/80). What seems to happen is when the image reflector requests the latest tags with the `n=1000` tag, the request does not contain the port. 

All image repositories which have less than 1000 tags do not cause an error, so I presume still include the port.

We are running Nexus3 OSS repo manager (v 3.22) in case it makes a difference.

Image repository:
```
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: not-working-image-repository
  namespace: flux-system
spec:
  image: <repo>:5000/<not-working-image>
  interval: 1m0s
  secretRef:
    name: docker-registry-credentials-image-automator
```

Note that working image repos seem to differ in ONLY the image name.

Error:

```
{
  "level": "error",
  "ts": "2023-02-16T14:30:05.582Z",
  "msg": "Reconciler error",
  "controller": "imagerepository",
  "controllerGroup": "image.toolkit.fluxcd.io",
  "controllerKind": "ImageRepository",
  "ImageRepository": {
    "name": "not-working-image-repository",
    "namespace": "flux-system"
  },
  "namespace": "flux-system",
  "name": "not-working-image-repository",
  "reconcileID": "8c492911-547a-4077-b438-fae9ec0f3b71",
  "error": "GET https://<repo>/v2/<not-working-image>/tags/list?last=not-working-tag-b1ee0122-462089352&n=1000: unexpected status code 404 Not Found: \n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>404 - Nexus Repository Manager</title><SNIP.. 404 html..>",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.14.2/pkg/internal/controller/controller.go:235"
}
```

Image repository which works:
```
curl "https://<repo>:5000/v2/<working-image>/tags/list" | jq '.tags | length'
391
```

Image repository which does not work:
```
curl "https://<repo>:5000/v2/<not-working-image>/tags/list" | jq '.tags | length'
1039
```

Great work on flux! We use it every day at work and it has been pretty solid for the last year!
