### ISSUE TITLE
Feature request: Add policy for selecting as latest any alias tag that matches the `latest` tag

### ISSUE THREAD

**Issue by aristapimenta** [fluxcd/image-reflector-controller#370]
When pushing new release tags to image repositories, it's a common practice to also update the special tag `latest` to the new release tag being pushed.

It would be really nice if `ImagePolicy` could have a policy option for selecting as latest some specific alias tag that points to the same image currently pointed by the `latest` tag.

My company uses git commit SHAs as image tags, and none of the three current policy options work great for this use case. For example:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    latestAlias: true
```

Then when I push the tag `90780e5f8f821983cdab22a6a528154e2e00a935` and also update `latest` to point to this tag, then `90780e5f8f821983cdab22a6a528154e2e00a935` becomes the latest tag choice of this policy.

This works much better than simply hardcoding `imgrepo:latest` in the deployment, because `imgrepo:latest` doesn't cause the pods to be restarted with a newer image when the `latest` tag is updated. By using the image update automation features of Flux I would be able to be specific with which version I'm running, and also cause the pods to be restarted with a newer version when the `latest` tag is updated in the image repository (because this event would be reflected as a config change in the deployment with the specific alias tag selected by the policy).

What if there are multiple tags matching the special tag `latest` at the moment? Which one to choose? For my specific use case this wouldn't happen, but for a more general solution then the same policy options already available could be applied for this subset of tags. For example:

```yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
spec:
  imageRepositoryRef:
    name: podinfo
  latestAlias: true
  policy:
    alphabetical:
      order: asc
```

In this case `latestAlias: true` moves up under `spec` and then after filtering the tags by this criterion the other policies available for picking a specific tag could be applied.

**Comment by aristapimenta** [comment]
By the way when I use the word "alias" here I don't mean any particular feature of any particular piece of software, I just mean that all the image tags pointing to the same concrete image can be considered "aliases" of each other, i.e. just the meaning in plain English.

**Comment by relu** [comment]
Hello @aristapimenta and thank you for submitting this feature request!

I think this could be a valid use case for situations where users don't have the ability to change the tagging format and can only rely on the `latest` or other rolling tags. However, for other situations, where the user does have the ability to control the tagging format, I think it would definitely be better to use [sortable image tags](https://fluxcd.io/flux/guides/sortable-image-tags/) as it can be way more convenient and predictable.

This could probably be implemented better as a policy type (calling it `rolling` [based on Bitnami's approach](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/#rolling-tags)) and once we have [latest tag digest](https://github.com/fluxcd/image-reflector-controller/pull/368) implemented, we could just use that in the image update automation rather than pick one of the other tags associated with the `latest` tagged image.

A possible spec would look like this:
```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo-latest
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    rolling:
      tag: latest # pointing to the tag to track
```

I would imagine a possible image automation configuration with setter markers would end up looking something like this: `image: podinfo:latest@sha256:<digest> # {"$imagepolicy": "flux-system:podinfo-latest"}` (note that this is not currently supported).

The only downside I see is that you will not be able to easily correlate the image tag back to the git commit from the workload state itself.

I'm positive this would work for your use case. Let me know what you think of this alternative implementation proposal.
