### ISSUE TITLE
Failed to authenticate to ACR

### ISSUE THREAD

**Issue by danieltoth55** [fluxcd/image-reflector-controller#371]
Hi,

I've been trying to set up image automation with Flux, but I got stuck with an error to authenticate to ACR.

I have an `ImageRepository` set up like this:
```
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: myrepo
  namespace: cluster-config
spec:
  image: myrepo.azurecr.io/my-service-image
  interval: 1m0s
  provider: azure
```
The error I'm getting:
```
  Warning  AuthenticationFailed  93s (x16 over 87m)  image-reflector-controller  failed to configure authentication options: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
  EnvironmentCredential: missing environment variable AZURE_TENANT_ID
  ManagedIdentityCredential: no default identity is assigned to this resource
  AzureCLICredential: Azure CLI not found on path
```

I'm using Terraform to deploy AKS and ACR, and the AzApi terraform provider to bootstrap Flux with the following config:
```
resource "azapi_resource" "flux_addon" {
  type      = "Microsoft.KubernetesConfiguration/extensions@2022-11-01"
  name      = "flux"
  parent_id = azurerm_kubernetes_cluster.aks_cluster.id
  locks     = [azurerm_kubernetes_cluster.aks_cluster.id]
  body = jsonencode({
    properties = {
      extensionType           = "microsoft.flux"
      autoUpgradeMinorVersion = true
      scope : {
        cluster : {
          releaseNamespace : var.flux_addon_cluster_release_namespace
        }
      }
      configurationSettings : {
        "helm-controller.enabled" : "true"
        "source-controller.enabled" : "true"
        "kustomize-controller.enabled" : "true"
        "notification-controller.enabled" : "true"
        "image-automation-controller.enabled" : "true"
        "image-reflector-controller.enabled" : "true"
      }
      configurationProtectedSettings : {}
    }
  })
```
I have found similar issues (https://github.com/fluxcd/source-controller/issues/898, https://github.com/fluxcd/source-controller/issues/1071), so I know that the problem is that I have multiple UAMIs set up in AKS, but I don't know how to set the environment variable `AZURE_CLIENT_ID` to the object id of the kubelet identity (kubelet identity has `AcrPull` role assignment), because I'm using the AKS Flux extension.

AKS configuration:
```
Kubernetes version: 1.25.4
Authentication and Authorization: Azure AD authentication with Azure RBAC
Network Plugin: Azure CNI
Add-ons: AzureKeyvaultSecretsProvider, ExtensionManager, omsagent
```

Flux version:
```
 ~  flux version
fluent-bit: 1.7.3
flux: v0.41.2
fluxconfig-agent: 1.7.3
fluxconfig-controller: 1.7.3
helm-controller: v0.31.2
image-automation-controller: v0.31.0
image-reflector-controller: v0.26.1
kustomize-controller: v0.35.1
notification-controller: v0.33.0
source-controller: v0.36.1
```

I know that this is somewhat of an Azure related issue, but even if I used another method to bootstrap Flux I would need to patch the `Deployment` and set the needed environment variable. I think there should be an easier way to do that.

Thanks!

**Comment by ba-work** [comment]
@danieltoth55 I'm seeing the same thing as you (and that led me here) I ended up solving it using a patch, as you mentioned. I deploy flux with a terraform module, but the end result is a kustomization that looks like this:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=20
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=5s
  target:
    kind: Deployment
    name: "(kustomize-controller|helm-controller|source-controller)"
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/1
      value:
        name: AZURE_CLIENT_ID
        value: <aks cluster's kubelet client id>
  target:
    kind: Deployment
    name: image-reflector-controller
```

**Comment by Lingkar** [comment]
I found the following AKS flux_addon configuration "--config useKubeletIdentity=true" (I have it setup with terraform).
[Microsoft Flux2 tutorial](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#using-kubelet-identity-as-authentication-method-for-aks-clusters)

This solved my image-reflector-controller authentication error, which was the same as @danieltoth55.

**Comment by lantern-sam** [comment]
> I found the following AKS flux_addon configuration "--config useKubeletIdentity=true" (I have it setup with terraform). [Microsoft Flux2 tutorial](https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#using-kubelet-identity-as-authentication-method-for-aks-clusters)
> 
> This solved my image-reflector-controller authentication error, which was the same as @danieltoth55.

This is the correct solution for most of the threads I've seen on this issue! (I've gone through so many today trying to fix this)

I'm not sure where it would quite fix but any addition to the documentation would be nice.

Thanks @Lingkar

**Comment by LukaszRacon** [comment]
You can also use managed identity/workload identity since v1.8.0:
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2?tabs=azure-cli#workload-identity-in-aks-clusters

**Comment by oscarwest** [comment]
For Managed Identity you can patch like this as well:

image-reflector-controller-patch.yaml
```
# Since we have multiple managed identities on the kubelets we need to let flux know which one to use for ACR access
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: AZURE_CLIENT_ID
            value: "0000-0000-0000-0000"

          
```
kustomization.yaml (next to gotk-*)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: other-patch.yaml
- path: image-reflector-controller-patch.yaml

```
