### ISSUE TITLE
ImageRepository status.lastScanResult.latestTags not sorted acc. to semver

### ISSUE THREAD

**Issue by heubeck** [fluxcd/image-reflector-controller#443]
Hey there, 
thank you very much for you great effort with flux.

Now the 'bug' :innocent: : my `ImageRepository` status looks like:

```
status:
  lastScanResult:
    latestTags:
      - 2.9.5
      - 2.9.4
      - 2.9.3
      - 2.9.2
      - 2.9.1
      - 2.9.0
      - 2.8.9
      - 2.8.8
      - 2.8.7
      - 2.8.6
    tagCount: 50
```

but actually there are newer tags `2.10.x`, also the related ImagePolicy is fine with `status.latestImage: my-image:2.10.14`.

Seems like the sorting of the `latestTags` is alphabetical rather than semver numeric.
