### ISSUE TITLE
Regular expression filtering

### ISSUE THREAD

**Issue by squaremo** [fluxcd/image-reflector-controller#73]
People occasionally want to partition their container image repo and use only a subset of the images. For example, by giving all the images destined for a dev environment a prefix `dev-`.

To give those people a way to filter for the desired subset of images, we can let them supply a regular expression in their `ImagePolicy` spec, and consider only the tags that match the regular expression.

They may also want to use only a portion of the tag for sorting, e.g., if the sort order is CalVer but there is a prefix, like `dev-2021-01-11.build-1`. Therefore it's useful to be able to sort using a particular capture group from the regular expression, or more generally, a replacement expression.

**Why not globbing?**

Globs are simpler to understand -- `dev-*` -- but suffer from a couple of problems:

 1. Libraries don't support captures, so the second requirement above would be tricky;
 2. They are not as general as regular expressions, e.g., it's not possible to filter for things that are CalVer-tagged.

If we implemented globs, we would very likely be asked to also implement regexp -- this is what happened for Flux v1. In the context of image tags, which don't have path separators (so no `**` glob pattern), it is not difficult to construct a regular expression that's equivalent to a glob: `dev-.*` for `dev-*` and so on.

**Place in the API**

https://github.com/fluxcd/image-reflector-controller/pull/58#issuecomment-736544317 and the comment following it https://github.com/fluxcd/image-reflector-controller/pull/58#issuecomment-736652343 suggest that filtering is independent of the ordering. It can either appear in each policy:

```yaml
spec:
  policy:
    semver:
      range: 1.x
      filterRegex: 'dev-v(.*)'
      sortOn: '\1'
```

or it can appear alongside the policy:

```yaml
spec:
  filterRegex: 'dev-v(.*)'
  sortOn: '\1'
  policy:
    semver:
      range: 1.x
```

There's a sense in which the filtering takes place _before_ the policy (e.g., extract the version portion of the tag before checking the semver range), so the latter feels closer to how people might think about it.

**Comment by squaremo** [comment]
`sortOn` isn't quite right -- maybe (in whichever bit of structure):

```yaml
filter:
  pattern: 'dev-(.*)'
  extract: '\1'
```
